set_property PACKAGE_PIN L4 [get_ports c]
set_property PACKAGE_PIN M4 [get_ports s]
set_property PACKAGE_PIN K4 [get_ports x]
set_property PACKAGE_PIN N8 [get_ports y]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports s]
set_property IOSTANDARD LVCMOS33 [get_ports x]
set_property IOSTANDARD LVCMOS33 [get_ports y]
